---
title: "Generating Plots for Prostate Cancer Analysis"
author: "Flemming Wu"
subtitle: "Using DESeq2 for the DE Analysis"
output: html_document
---

```{r setup, include=FALSE}
if (Sys.info()["sysname"] == "Windows") {
  knitr::opts_chunk$set(root.dir="~/velvilab/P_Ca_Secondary")
} else if (Sys.info()["sysname"] == "Darwin") {
  knitr::opts_chunk$set(rroot.dir="~/Desktop/velvilab/P_Ca_Analysis")
}
knitr::opts_chunk$set(fig.width=12, fig.height=12, echo=TRUE)
```

## Load libraries and set up data

```{r message=F}
library(tidyverse)
library(RUVSeq)
library(readxl)
library(RColorBrewer)
library(EnsDb.Hsapiens.v86)
library(org.Hs.eg.db)
library(EnhancedVolcano)
library(ggpubr)
library(clusterProfiler)
library(enrichplot)
library(DESeq2)
library(patchwork)
library(openxlsx)
library(gridExtra)
library(msigdbr)
```

```{r}
key <- read_xlsx("./Manifest/P_Ca_sec_manifest_030923.xlsx")
test.file <- read.table(file="./Count_Table/ENRIQUERNA_0001_01_PROSTATE_SRR10238298_C1_NEBKAP_A00001.proj.Aligned.out.sorted.md.bam.htSeqCounts")

df <- as.data.frame(matrix(0, ncol = 0, nrow = nrow(test.file)))
for (i in list.files(path="./Count_Table")) {
  name <- str_extract(i, "SRR[0-9]{8}")
  df[[name]] <- read.table(file=paste0("./Count_Table/",i)) %>% pull(V2) # read in vector of counts to new column
}

# assign gene names to the row names
row.names(df) <- test.file$V1 

# assign African American or Caucasian American to sample names
names(df) <- ifelse(names(df) %in% key$`African American`, paste(names(df), "Afr", sep="_"), paste(names(df), "Cau", sep="_"))
```



## Run pipeline

```{r define functions}
addGeneSym <- function(df) {
  # remove "." from ensembl gene id
  rownames(df) <- sub("\\.[0-9]*$", "", rownames(df))
  # map ensembl geneid to gene symbol
  geneids <- ensembldb::select(x = EnsDb.Hsapiens.v86,  key=rownames(df), columns=c("SYMBOL"), keytype="GENEID")
  rownames(geneids) <- geneids$GENEID
  
  # merge mapping back to original dataframe
  df <- merge(x = df, y = geneids, by = "row.names", all = TRUE) %>%
    column_to_rownames(var = "Row.names") %>%
    relocate(SYMBOL, .before = baseMean) %>%
    dplyr::select(!starts_with("GENEID"))
  
  return(df)
}
```

```{r warning=F}
df <- df[apply(df, 1, function(x) length(x[x>5])>=15),]

x <- names(df) %>% str_extract("Afr$|Cau$") %>% as.factor()
set <- newSeqExpressionSet(as.matrix(df), phenoData = data.frame(x, row.names = colnames(df)))

set <- betweenLaneNormalization(set, which = "upper")

design <- model.matrix(~x, data=pData(set))
y <- DGEList(counts=counts(set), group=x)
y <- calcNormFactors(y, method="upperquartile")
y <- estimateGLMCommonDisp(y, design)
y <- estimateGLMTagwiseDisp(y, design)
fit <- glmFit(y, design)
res <- residuals(fit, type="deviance")

set2 <- RUVr(set, rownames(set), k=9, res)

dds <- DESeqDataSetFromMatrix(countData = counts(set2), colData = pData(set2), design = ~W_1 + x)
dds <- DESeq(dds)
res <- results(dds)
res <- na.omit(res)
res <- res[res$baseMean > 50,] # filter out lowly expressed genes to reduce noise

df.res <- as.data.frame(res) %>% arrange(pvalue)

df.res.sym <- addGeneSym(df.res)
df.res.sym <- arrange(df.res.sym, pvalue)
```

```{r}
if (!file.exists("./gene-lists/full-gene-list.xlsx")) {
  write.xlsx(rownames_to_column(df.res.sym), "./gene-lists/full-gene-list.xlsx")
}
```


---

## Volcano Plot

```{r}
p1 <- EnhancedVolcano(df.res.sym, x = "log2FoldChange", y = "pvalue", lab = df.res.sym$SYMBOL,
                title = "African American (reference) vs Caucasian American (comparison) - DESeq2",
                subtitle = "p-value cutoff: 0.05 | log2-fold change cutoff: 1",
                col = c("gray", "#4bd0fe", "red1", "#fef84b")
)

p1

if (!file.exists('./figures/volcano_plot.jpeg')) {
  ggsave(
    filename='./figures/volcano_plot.jpeg',
    plot=p1, dpi=800, width = 20, height = 20,
    units = "in"
  )
}
```


## MA Plot

```{r}
to.plot <- df.res.sym %>%
  mutate(baseMean = log2(baseMean)) %>%
  dplyr::rename(baseMeanLog2 = baseMean)
  
p2 <- ggmaplot(data = to.plot, 
           main = "African American (reference) vs Caucasian American (comparison) - DESeq2",
           fdr = 0.1, fc = 2, size = 0.4,
           palette = c("#7AFF96", "#FF7A7A", "darkgray"),
           genenames = to.plot$SYMBOL,
           legend = "top", top = 50,
           select.top.method = "padj",
           font.label = c("bold", 9), label.rectangle = FALSE,
           font.legend = "bold",
           font.main = "bold",
           xlab = "log2 Base Mean",
           ggtheme = ggplot2::theme_minimal()
           ) + labs(subtitle = "Top 50 p-adjusted genes labeled")

p2

if (!file.exists('./figures/ma_plot.jpeg')) {
  ggsave(
    filename='./figures/ma_plot.jpeg',
    plot=p2, dpi=800, width = 20, height = 15,
    units = "in"
  )
}
```


## GSEA

```{r}
ranked.gene.list <- df.res %>%
  mutate(rank = log2FoldChange * -log10(pvalue)) %>% ## here I rank by multiplying logFC by -log10(pvalue) to give more weight to more significant genes
  rownames_to_column(var = "ENSEMBL") %>% 
  mutate(ENSEMBL = str_replace(ENSEMBL, ".[0-9]{1,2}$", "")) %>% 
  dplyr::select(ENSEMBL, stat) %>%
  arrange(-stat) %>%
  tibble::deframe()

gse.go <- gseGO(geneList = ranked.gene.list, OrgDb = org.Hs.eg.db, keyType = "ENSEMBL", minGSSize = 10,
      maxGSSize = 500, nPermSimple = 10000, pvalueCutoff = 0.05, eps = 1e-300, verbose = F)
```


```{r}
if (!file.exists("./pathways/GSEA_GO_pathways.xlsx")) {
  write.xlsx(as.data.frame(gse.go), "./pathways/GSEA_GO_pathways.xlsx")
}
```

```{r}
filter(gse.go, enrichmentScore > 0) %>%
  as.data.frame()
```

```{r}
gseaplot2(gse.go, geneSetID = 1:10, pvalue_table = TRUE, title = "GSEA plot - Top 10 Upregulated Pathways in Caucasian Americans")

if (!file.exists("./figures/GSEA_upregulated_ca_plot.jpeg")) {
  jpeg(file="./figures/GSEA_upregulated_ca_plot.jpeg", res = 800, width = 15, height = 15, units = "in")
  gseaplot2(gse.go, geneSetID = 1:10, pvalue_table = TRUE, title = "GSEA plot - Top 10 Upregulated Pathways in Caucasian Americans")
  dev.off()
}
```

```{r}
gseaplot2(filter(gse.go, enrichmentScore < 0), geneSetID = 1:10, pvalue_table = TRUE, title = "GSEA plot - Top 10 Upregulated Pathways in African Americans")

if (!file.exists("./figures/GSEA_upregulated_aa_plot.jpeg")) {
  jpeg(file="./figures/GSEA_upregulated_aa_plot.jpeg", res = 800, width = 15, height = 15, units = "in")
  gseaplot2(filter(gse.go, enrichmentScore < 0), geneSetID = 1:10, pvalue_table = TRUE, title = "GSEA plot - Top 10 Upregulated Pathways in African Americans")
  dev.off()
}
```

```{r}
dp <- dotplot(gse.go, split=".sign", showCategory = 20) + facet_grid(.~.sign) + labs(title = "African American (reference) vs Caucasian American (comparison)", subtitle = "GSEA - GO:BP")

if(!file.exists("./figures/GSEA_dotplot.jpeg")) {
  ggsave(filename="./figures/GSEA_dotplot.jpeg", dp, dpi = 800, width = 12, height = 15, units = "in")
}
```

```{r}
cnp <- cnetplot(setReadable(gse.go, 'org.Hs.eg.db', 'auto'), showCategory = 10)

if(!file.exists("./figures/GSEA_cnetplot.jpeg")) {
  ggsave(filename="./figures/GSEA_cnetplot.jpeg", cnp, dpi = 800, width = 30, height = 30, units = "in")
}
```

```{r message=F}
rp <- ridgeplot(gse.go) + 
  labs(x = "enrichment distribution") + 
  scale_fill_gradient(low = "#e6f43c", high = "#ff4a4a") + 
  labs(title = "African American (reference) vs Caucasian American (comparison)", subtitle = "GSEA - GO:BP")

if(!file.exists("./figures/GSEA_ridgeplot.jpeg")) {
  ggsave(filename="./figures/GSEA_ridgeplot.jpeg", rp, dpi = 800, width = 15, height = 15, units = "in")
}
```

```{r}
gse.go <- pairwise_termsim(gse.go)
emp <- emapplot(gse.go, cex_category=1.5, showCategory = 50)

if(!file.exists("./figures/GSEA_emapplot.jpeg")) {
  ggsave(filename="./figures/GSEA_emapplot.jpeg", emp, dpi = 800, width = 20, height = 20, units = "in")
}
```

```{r}
usp <- upsetplot(gse.go, n = 15)

if(!file.exists("./figures/GSEA_upsetplot.jpeg")) {
  ggsave(filename="./figures/GSEA_upsetplot.jpeg", usp, dpi = 800, width = 20, height = 10, units = "in")
}
```


```{r}
# separate gene lists
p.05.up <- filter(df.res.sym, (pvalue < 0.05) & (log2FoldChange > 0))
p.05.dn <- filter(df.res.sym, (pvalue < 0.05) & (log2FoldChange < 0))
p.01.up <- filter(df.res.sym, (pvalue < 0.01) & (log2FoldChange > 0))
p.01.dn <- filter(df.res.sym, (pvalue < 0.01) & (log2FoldChange < 0))
p.001.up <- filter(df.res.sym, (pvalue < 0.001) & (log2FoldChange > 0))
p.001.dn <- filter(df.res.sym, (pvalue < 0.001) & (log2FoldChange < 0))
fdr.1.up <- filter(df.res.sym, (padj < 0.1) & (log2FoldChange > 0))
fdr.1.dn <- filter(df.res.sym, (padj < 0.1) & (log2FoldChange < 0))

filtered.res <- list("p.05.up" = p.05.up, "p.05.dn" = p.05.dn,
                     "p.01.up" = p.01.up, "p.01.dn" = p.01.dn,
                     "p.001.up" = p.001.up, "p.001.dn" = p.001.dn,
                     "fdr.1.up" = fdr.1.up, "fdr.1.dn" = fdr.1.dn)
if (!file.exists("./gene-lists/filtered_gene_lists.xlsx")) {
  write.xlsx(filtered.res, file = "./gene-lists/filtered_gene_lists.xlsx") 
}
```

